[profile.default]
 src = "contracts"
 test = "contracts"
 out = "out"
 libs = ["node_modules"]
remappings = [
  "@openzeppelin/=node_modules/@openzeppelin/",
  "forge-std/=node_modules/forge-std/src/"
]
optimizer = true
optimizer_runs = 200
via_ir = true
